title: AI Blog của tôi
email: your-email@example.com
description: >- 
  Blog chia sẻ kiến thức học AI
baseurl: "" # nếu không nằm trong subfolder
url: "https://<username>.github.io"
theme: minima

plugins:
  - jekyll-feed
